apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.service.expose: "true"
    kompose.service.type: nodeport
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: adminer
  name: adminer
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 8080
  selector:
    io.kompose.service: adminer
  type: NodePort
