apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.service.expose: "true"
    kompose.service.type: nodeport
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: strapi
  name: strapi
spec:
  ports:
    - name: "1339"
      port: 1339
      targetPort: 1337
  selector:
    io.kompose.service: strapi
  type: NodePort
