apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.service.expose: "true"
    kompose.service.type: nodeport
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: adminer
  name: adminer
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: adminer
                port:
                  number: 9092
            path: /
            pathType: Prefix
